queue_rules:
  - name: default
    conditions:
      - "label!=WIP"
      - "label!=do-not-merge"
      - status-success=format
      - "status-success~=compile \\([0-9]+\\)"
      - "status-success~=test \\([0-9]+\\)"

pull_request_rules:
  - name: Approve and label scala-steward's PRs
    conditions:
      - author=scala-steward
      - head~=^update/
    actions:
      label:
        add:
          - dependencies
          - mergify:squash
      review:
        type: APPROVE

  - name: Approve and label Dependabot's PRs
    conditions:
      - author=dependabot
      - head~=^dependabot/
    actions:
      label:
        add:
          - dependencies
          - mergify:squash
      review:
        type: APPROVE

  - name: Squash PRs into master
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=mergify:squash"
    actions:
      queue:
        method: squash
        name: default

  - name: Merge PRs into master
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=mergify:merge"
    actions:
      queue:
        method: merge
        name: default

  - name: Delete head branch on merge
    conditions:
      - merged
    actions:
      delete_head_branch:
        force: false
