queue_rules:
  - name: duplicated default from Merge PRs into master
    queue_conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=mergify:squash"
      - base=master
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=mergify:merge"
    merge_conditions: []
    merge_method: merge
  - name: default
    queue_conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label=mergify:squash"
    merge_conditions:
      - "label!=WIP"
      - "label!=do-not-merge"
      - status-success=format
      - "status-success~=compile \\([0-9]+\\)"
      - "status-success~=test \\([0-9]+\\)"
    merge_method: squash

pull_request_rules:
  - name: Approve and label scala-steward's PRs
    conditions:
      - author=scala-steward
      - head~=^update/
    actions:
      label:
        add:
          - dependencies
          - mergify:squash
      review:
        type: APPROVE

  - name: Approve and label Dependabot's PRs
    conditions:
      - author=dependabot[bot]
      - head~=^dependabot/
    actions:
      label:
        add:
          - dependencies
          - mergify:squash
      review:
        type: APPROVE

  - name: Delete head branch on merge
    conditions:
      - merged
    actions:
      delete_head_branch:
        force: false
  - name: Merge PRs into master + Squash PRs into master
    conditions: []
    actions:
      queue:
